/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class moe_lemonneko_nekogit_cmds_CloneCommand */

#ifndef _Included_moe_lemonneko_nekogit_cmds_CloneCommand
#define _Included_moe_lemonneko_nekogit_cmds_CloneCommand
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     moe_lemonneko_nekogit_cmds_CloneCommand
 * Method:    doClone
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lmoe/lemonneko/nekogit/cmds/CloneCommand/OnProgressListener;Lmoe/lemonneko/nekogit/cmds/Command/OnErrorListener;)I
 */
JNIEXPORT jint JNICALL Java_moe_lemonneko_nekogit_cmds_CloneCommand_doClone
  (JNIEnv *, jobject, jstring, jstring, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
