/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class moe_lemonneko_nekogit_cmds_GitClone */

#ifndef _Included_moe_lemonneko_nekogit_cmds_GitClone
#define _Included_moe_lemonneko_nekogit_cmds_GitClone
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     moe_lemonneko_nekogit_cmds_GitClone
 * Method:    doClone
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lmoe/lemonneko/nekogit/cmds/GitClone/FetchCallback;Lmoe/lemonneko/nekogit/cmds/GitClone/CheckoutCallback;Lmoe/lemonneko/nekogit/cmds/GitClone/ErrorCallback;)V
 */
JNIEXPORT void JNICALL Java_moe_lemonneko_nekogit_cmds_GitClone_doClone
        (JNIEnv *, jclass, jstring, jstring, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
